package src.model.Exceptions;

/**
 * Custom exception class that indicates a failure to add a finding.
 * <p>
 * This exception is thrown when an operation to add a finding object to a path fails due to various reasons.
 * <p>
 * <b>Pre-condition:</b> An exception must be passed to the constructor.
 * <p>
 * <b>Post-condition:</b> A new exception of type {@code FailedToAddFindingException} is created with a custom message.
 */
public class FailedToAddFindingException extends Exception{
    /**
     * Constructs a new {@code FailedToAddFindingException} with the specified cause.
     * <p>
     * The message is generated by appending the provided exception message to a standard prefix.
     *
     * @param message The {@link Exception} that caused this exception to be thrown.
     * @see Exception
     */
    public FailedToAddFindingException(Exception message){
        super("Failed to add finding: " + message);
    }
}
